# Generated by Django 4.1.3 on 2023-05-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTracker',
            fields=[
                ('financial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('income_sum', models.IntegerField()),
                ('expenses_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=150)),
                ('create_data', models.DateField()),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('create_date', models.DateField()),
                ('last_changes_date', models.DateField()),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListElement',
            fields=[
                ('list_element_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=130)),
                ('do', models.BooleanField()),
                ('fk_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=180)),
                ('upload_data', models.DateField()),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessNote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.note')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessFinancialTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
