# Generated by Django 4.1.3 on 2023-05-29 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='fk_user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_changes_date',
        ),
        migrations.AddField(
            model_name='note',
            name='allowed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CanAccessNote',
        ),
    ]
