# Generated by Django 4.1.3 on 2023-05-30 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0002_remove_note_fk_user_remove_note_last_changes_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_event', models.DateTimeField()),
                ('finish_event', models.DateTimeField()),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
