# Generated by Django 4.2.1 on 2023-05-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0002_image_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
