# Generated by Django 4.1.3 on 2023-06-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0003_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
