# Generated by Django 4.2.1 on 2023-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0003_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_data',
            field=models.DateField(),
        ),
    ]
