# Generated by Django 4.1.3 on 2023-05-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0005_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
