# Generated by Django 4.1.3 on 2023-06-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0006_remove_canaccesslist_fk_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('create_data', models.DateField()),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListElement',
            fields=[
                ('list_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=130)),
                ('do', models.BooleanField(default=False)),
                ('fk_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list')),
            ],
        ),
    ]
