# Generated by Django 4.1.3 on 2023-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0006_delete_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='image_id',
        ),
    ]
