# Generated by Django 4.2.1 on 2023-05-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0007_rename_id_image_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=150)),
                ('create_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ListElement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=130)),
                ('do', models.BooleanField()),
                ('fk_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list')),
            ],
        ),
    ]
