# Generated by Django 4.1.3 on 2023-06-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0007_list_listelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
