# Generated by Django 4.2.1 on 2023-05-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0008_list_listelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='id',
            new_name='list_id',
        ),
        migrations.RenameField(
            model_name='listelement',
            old_name='id',
            new_name='list_element_id',
        ),
    ]
