# Generated by Django 4.1.3 on 2023-06-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0008_rename_create_data_list_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listelement',
            name='do',
            field=models.BooleanField(),
        ),
    ]
