# Generated by Django 4.1.3 on 2023-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0009_alter_listelement_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelement',
            name='create_date',
            field=models.DateField(default='2023-06-14'),
            preserve_default=False,
        ),
    ]
