# Generated by Django 4.2.1 on 2023-05-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0009_rename_id_list_list_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTracker',
            fields=[
                ('financial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('income_sum', models.IntegerField()),
                ('expenses_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('reset_password', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='listelement',
            name='fk_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('create_date', models.DateField()),
                ('last_changes_date', models.DateField()),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessNote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.note')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.list')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.image')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CanAccessFinancialTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('autorized_data', models.DateField()),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user'),
        ),
        migrations.AddField(
            model_name='list',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.user'),
        ),
    ]
