# Generated by Django 4.1.3 on 2023-06-22 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0010_listelement_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTracker',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('fk_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickshare_api.financialtracker')),
            ],
        ),
    ]
