# Generated by Django 4.1.3 on 2023-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0012_remove_expenses_fk_financial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
