# Generated by Django 4.1.3 on 2023-06-27 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0013_remove_image_image_name_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='allowed',
        ),
        migrations.AddField(
            model_name='calendar',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
