# Generated by Django 4.1.3 on 2023-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0014_remove_calendar_allowed_calendar_fk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='finish_event',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='start_event',
        ),
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateField(default='2023-05-12'),
        ),
    ]
