# Generated by Django 4.1.3 on 2023-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0015_remove_calendar_finish_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(),
        ),
    ]
