# Generated by Django 4.1.3 on 2023-06-29 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickshare_api', '0017_remove_calendar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('data', models.DateField()),
                ('fk_user_creator', models.IntegerField()),
                ('allowed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
