# Generated by Django 4.1.3 on 2023-06-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare_api', '0018_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
